"""comment table update

Revision ID: 0f8406412a6f
Revises: cc5e1df8b7c6
Create Date: 2023-08-02 14:02:37.573137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0f8406412a6f'
down_revision = 'cc5e1df8b7c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('recommendation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'recommendation', ['recommendation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'recommendation_id')
    # ### end Alembic commands ###
