"""slug on fiction type

Revision ID: 8f915c808a34
Revises: c8c4b10049f6
Create Date: 2023-08-02 09:03:27.482602

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8f915c808a34'
down_revision = 'c8c4b10049f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction_type', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False))
    op.create_unique_constraint(None, 'fiction_type', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiction_type', type_='unique')
    op.drop_column('fiction_type', 'slug')
    # ### end Alembic commands ###
