"""unique together on reaction table

Revision ID: ea2d41cc5a1f
Revises: eaee92299e7c
Create Date: 2023-08-02 16:25:12.581337

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ea2d41cc5a1f'
down_revision = 'eaee92299e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_recommendation_uc', 'reaction', ['user_id', 'recommendation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_recommendation_uc', 'reaction', type_='unique')
    # ### end Alembic commands ###
